### ISSUE TITLE
Allow defining custom synopsis

### ISSUE THREAD

**Issue by marcingrzejszczak** [zdharma/zshelldoc#1]
Currently by default (https://github.com/zdharma/zshelldoc/blob/master/src/zsd-to-adoc.main#L85) we get the `Documentation automatically generated with zshelldoc`. It would be great to provide an option to pass custom synopsis. That way we can provide some insight into each script.

BTW this framework is awesome and we're using it in Spring Cloud Pipelines (https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/README.adoc)

**Comment by psprint** [comment]
I've added option `--synopsis`. It outputs into document with processing of escape codes like `\n`. To output multi-line text Asciidoctor syntax can be used together with `\n`, `--help` and README explain how to do it.

I'm very happy that Zshelldoc managed to process your large documentation in a way that's useful. I've somewhat stopped development when my own docs we're generated fine, assuming I will respond to user requests and this way do a development that's reality-driven , not my-own-ideas-driven :) So if you have more feature requests, I can help.

**Comment by marcingrzejszczak** [comment]
That's awesome! I wonder however if it wouldn't be even more cool if the `synopsis` section could be read from the script. So that function documentation and synopsis could be written in each script. Cause otherwise I need to provide that option per each file. 

So that you have a better understanding of how we use it - https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/tools/build-helper.sh#L68-L83 (maybe I'm using it in a wrong way). We're batch reading all files from a folder so I'd want the synopsis to be set per each file and read from that file. We could do sth like

```
# synopsis {{{
# this line should end up in synopsis
# }}}
```

WDYT?

**Comment by psprint** [comment]
It's a good idea, I've implemented it. It works like you requested:

```
# synopsis {{{
# Hello world +
# Second line
# }}}
```

String "synopsis" is compared in case insensitive manner, the delimeters `{{{`, `}}}` can be customized with options `--blocka`, `--blockb`.

**Comment by marcingrzejszczak** [comment]
Hmm I almost have it working. The synopsis seems to be picked from a wrong spot.

Synopsis: https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L7-L35

How we run it: https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/tools/build-helper.sh#L77

Wrong synopsis: https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/zsdoc/pipeline.sh.adoc#synopsis

Taken actually from here: https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L425-L428

**Comment by psprint** [comment]
The matching was greedy so "*" was matching far far after "synosis {{{" :) I've switched to non-greedy, it seems to generate OK now (I've tested on your script). With one thing, some AsciiDoc formating is needed to have proper lists and so.

**Comment by marcingrzejszczak** [comment]
Looks really good now. I wonder about last thing. https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/zsdoc/pipeline.sh.adoc#build We could get rid of the `#` in all function descriptions. WDYT?

**Comment by psprint** [comment]
I've started new issue for this. It is implemented via new `--scomm` option. Lets continue there or in new issues.

Side to coding, could I kindly ask for a symbolic donation? I have a patreon profile https://www.patreon.com/psprint and a [PayPal button](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=H4GZAACT2MQ3W). In anyway thanks for interest in Zshelldoc.

**Comment by marcingrzejszczak** [comment]
Done :) Swietna robota!
