### ISSUE TITLE
`[[` not in sh

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zshelldoc#7]
I see a shebang as `/bin/sh` but I don't think it supports the `[[` conditional.

https://github.com/zdharma/zshelldoc/blob/master/src/zsd.preamble#L10 :
```
if [[ -f /usr/local/share/zshelldoc/zsd.config ]]; then
  . /usr/local/share/zshelldoc/zsd.config
elif [[ -f /usr/share/zshelldoc/zsd.config ]]; then
  . /usr/share/zshelldoc/zsd.config
elif [[ -f /opt/share/zshelldoc/zsd.config ]]; then
  . /opt/share/zshelldoc/zsd.config
fi
```

So I get this:

```
/home/robo/.local/bin/zsd: 10: /home/robo/.local/bin/zsd: [[: not found
/home/robo/.local/bin/zsd: 12: /home/robo/.local/bin/zsd: [[: not found
/home/robo/.local/bin/zsd: 14: /home/robo/.local/bin/zsd: [[: not found
```
etc...

(Ubuntu supplies `sh` via dash I think)

**Comment by psprint** [comment]
Thanks, I've updated the block and verified it with `checkbashism`, it still reports one problem (lack of `${var/.../...}` substitution in POSIX shell), but I'm counting that dash might implement it

**Comment by robobenklein** [comment]
Seems good to go! thanks
