### ISSUE TITLE
Feature request: `env-vars` section merging

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zshelldoc#8]
It appears that when multiple `env-vars` sections are present, only one gets loaded. Since it's in an association format already, how hard would it be to merge sections together?

I'd be fine with adding a different section (`env-merge`?) that has a different type of syntax to make this parsing easier.

Example use case where I'm placing variable descriptions at the location of setting the default for it:

```shell
# env-vars {{{
typeset -gA p10ks_battery
p10ks_battery[percent]=""
# p10ks_battery[verbose] -> 0/1: enables showing time until full/empty (requiress acpi)
p10ks_battery[verbose]="${p10ks_battery[verbose]:-1}"
# }}}

<stuff>

# env-vars {{{
[[ "${(t)p10ks_battery}" != "association" ]] && {
  typeset -gA p10ks_battery
}
p10ks_battery[threshold_low]=${p10ks_battery[threshold_low]:-"30"}
# p10ks_battery[fgcolor_low] -> color of text when battery below threshold_low
p10ks_battery[fgcolor_low]="${p10ks_battery[fgcolor_low]:-black}"
# p10ks_battery[fgcolor_charging] -> color of text when charging
p10ks_battery[fgcolor_charging]="${p10ks_battery[fgcolor_charging]:-green}"
# p10ks_battery[fgcolor_default] -> default foreground color
p10ks_battery[fgcolor_default]="${p10ks_battery[fgcolor_default]:-white}"
# }}}
```

My immediate thought is to split on the first ` -> ` and then do a string-to-string zsh associate array, then a loop through it at the end to put it all back into the same asciidoc format.

**Comment by robobenklein** [comment]
Also, I know this might not be possible with zsh assoc. arrays, but it would be nice to keep the ordering of the variables as they are presented in the file.

**Comment by psprint** [comment]
It is done (what's left is only keeping the order). Surprisingly for me, the usage that mixes env-vars lines and Zsh code does work correctly 👍. Sorry if the delay was too long.

**Comment by robobenklein** [comment]
Thanks! Now writing more docs for P10K
